[package]
name = "dozclock"
version = "1.0.0"
authors = ["Agiel <agiel.negura@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
radix_fmt = "1.0.0"
clap = "3.0.0-beta.1"
